image: quay.io/gitpodified-workspace-images/full

tasks:
  - name: Dev Server
    init: |
      nvm install --lts
      nvm use --lts
      nvm alias default --lts
      nvm install-latest-npm
      npm i -g yarn
      yarn install
    command: yarn dev

ports:
  - port: 8080
    onOpen: notify

vscode:
  extensions:
    - eamodio.gitlens
    - arcanis.vscode-zipfs
