nodeLinker: 'node-modules' # Yes, it's pain.
yarnPath: .yarn/releases/yarn-berry.cjs

# This should fix most of the missing dependency errors these packages forget to declare
# in their manifest files.
packageExtensions:
  "@vue/babel-plugin-jsx@*":
    peerDependencies:
      "@babel/core": "*"
  "@vuepress/core@*":
    dependencies:
       "@vue/compiler-sfc": "*"
       "escape-html": "*"
  "vuepress@*":
    dependencies:
       "@vue/compiler-sfc": "*"
  "@vuepress/shared-utils@*":
    dependencies:
       "markdown-it-emoji": "*"
       "lru-cache": "*"
       "@vue/component-compiler-utils": "*"